# Site settings
title: Vitor Machado's blog
subtitle: "The random ramblings of a software developer"
email: vmachado@cos.ufrj.br
description: "Artificial Intelligence graduate from the Federal University of Rio de Janeiro, and software developer at CAPGov/COPPE. Photographer as a hobby, music lover and gamer since I was a little kid."
baseurl: ""
url: "http://vitormachado.me"
twitter_username: "VittauMach"
github_username:  "vittau"
instagram_username: "vitor.p.mach"

# Build settings
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

# Sass
sass:
    style: :compressed