# Site settings
title: Vitor Machado's blog
subtitle: "Ramblings of a software developer"
email: vmachado@cos.ufrj.br
description: "Artificial Intelligence graduate at the Federal University of Rio de Janeiro, and software tester at CAPGov/COPPE. So yeah, I like computers and pretty much anything that is related. Some of my other interests are music, photography, aviation and video-games."
baseurl: "/blog"
url: "http://vitormachado.me"
twitter_username: "VittauMach"
github_username:  "vittau"
instagram_username: "vitor.p.mach"

# Build settings
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

# Sass
sass:
    style: :compressed