# Site settings
title: The Random Ramblings of a Software Developer
subtitle: "A blog about computer stuff. Mostly."
author: "Vitor Machado"
email: vmachado@cos.ufrj.br
description: "I live in Curitiba, Brazil. I'm a software developer, A.I. Ph.D. student, music lover and gamer."
baseurl: "/blog"
url: "https://www.vitormach.dev"
image: "/img/avatar.png"
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is
twitter_username: "VittauMach"
github_username: "vittau"
instagram_username: "vitor.p.mach"
keywords: "blog,tech,developer"

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title

# Pagination
paginate: 5

# Sass
sass:
  style: :compressed
