# Site settings
title: The Random Ramblings of a Software Developer
subtitle: "Vitor Machado's blog about computer stuff. Mostly."
author: "Vitor Machado"
email: vmachado@cos.ufrj.br
description: "Artificial Intelligence graduate from the Federal University of Rio de Janeiro, and software developer at CAPGov/COPPE. Photographer as a hobby, music lover and gamer since I was a little kid."
baseurl: "/blog"
url: "https://vitorpmach.com"
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is
twitter_username: "VittauMach"
github_username:  "vittau"
instagram_username: "vitor.p.mach"
keywords: "blog,tech,developer"
fb_app_id: 1757810987867044

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title

# Pagination
paginate: 5

# Sass
sass:
    style: :compressed